1st task
js-tasks-ru/jsbasic-20220113_alexanderr24 pull request #1
Opened 2021-12-25 13:57 UTC by Alexander2464R

2021-12-25 13:57 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2021-12-25 14:00 UTC, Alexander2464R commented
function sum

2022-01-14 07:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-14 08:00 UTC, SinimaWath requested changes

2022-01-14 08:00 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(2,5);
Из задач, нужно убирать информацию для тестирования:

- Они могут поломать другие тесты
- В задачах не требуется, оставлять какой-то код, кроме необходимой функциональности.

Для тестирования, нужно использовать: npm test

2022-01-14 08:03 UTC, SinimaWath commented
Если добавил задачу, то ее нужно решить :)

2022-01-14 19:19 UTC, SinimaWath commented
Для первого модуля первой задачи  у тебя есть конфликт:
- Он появляется из-за того, что ты сделал одновременно два решения:
- Скачал решение преподавателя и написал свое.

Тут про конфликты можно https://githowto.com/ru/resolving_conflicts

2022-01-17 13:08 UTC, SinimaWath approved these changes
все ок!

2022-01-17 13:08 UTC, merged