Homework 5-module
js-tasks-ru/jsbasic-20220113_alexanderr24 pull request #6
Opened 2022-02-06 16:31 UTC by Alexander2464R

2022-02-06 16:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-06 17:02 UTC, SinimaWath requested changes

2022-02-06 17:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    if (offset != getSlidesWidth - getSlideWidth) offset += getSlideWidth;
- getSlideWidth, getSlidesWidth- это призыв к действию, так обычно называются функции. Нужно переименовать без get.
- Попробуй взять ширину carouselInner.

2022-02-06 17:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  });
Этого делать не нужно :) Размеры и так есть в carouselInner.offsetWidth

2022-02-06 17:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  });
Если хочешь получить всю ширину, можешь умножить getSlideWidth, на количество

2022-02-06 17:06 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    if (offset > 0) carouselArrowLeft.style.display = '';;
Попробуй логику скрывания стрелок, вынести в одну функцию и использовать ее в двух обработчиках:

`function hideArrows() {}`

2022-02-07 17:22 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-08 12:26 UTC, SinimaWath approved these changes

2022-02-08 12:26 UTC, merged